# Generated by Django 3.1 on 2020-08-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='Post',
        ),
    ]
