# Generated by Django 3.1 on 2020-08-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0002_auto_20200827_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Experience',
        ),
    ]
