# Generated by Django 3.1 on 2020-08-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0006_auto_20200828_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='institution',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
