# Generated by Django 2.2.4 on 2020-08-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0012_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
    ]
