# Generated by Django 3.1 on 2020-08-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0016_auto_20200829_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='positioning',
            field=models.CharField(default='', max_length=255),
        ),
    ]
