# Generated by Django 3.1 on 2020-08-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0018_auto_20200830_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.CharField(default='', max_length=255),
        ),
    ]
