# Generated by Django 3.1 on 2020-08-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0003_auto_20200827_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
