# Generated by Django 3.1 on 2020-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0004_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='detail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
