# Generated by Django 3.1 on 2020-08-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0008_personaldetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
    ]
