# Generated by Django 3.1 on 2020-08-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0009_delete_personaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='institution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
