# Generated by Django 3.1 on 2020-08-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0014_experience_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
    ]
