# Generated by Django 3.1 on 2020-08-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker', '0017_category_positioning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='positioning',
        ),
        migrations.AddField(
            model_name='experience',
            name='positioning',
            field=models.CharField(default='', max_length=255),
        ),
    ]
